<?php
declare(strict_types=1);
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type, Authorization, Accept, X-PMS-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') { http_response_code(204); exit; }
date_default_timezone_set('Asia/Makassar');

function env_map(string $path): array {
    $env = [];
    if (!is_file($path)) return $env;
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '#')) continue;
        $pos = strpos($line, '=');
        if ($pos === false) continue;
        $env[trim(substr($line, 0, $pos))] = trim(trim(substr($line, $pos + 1)), "\"'");
    }
    return $env;
}
function now_ts(): string { return date('Y-m-d H:i:s'); }
function today_date(): string { return date('Y-m-d'); }
function as_float(mixed $value): float { $n = (float) ($value ?? 0); return is_finite($n) ? $n : 0.0; }
function as_int(mixed $value): int { return (int) round(as_float($value)); }
function money(float $amount): string { return 'IDR ' . number_format($amount, 0, ',', '.'); }
function json_input(): array { static $data = null; if ($data !== null) return $data; $raw = file_get_contents('php://input') ?: ''; $decoded = json_decode($raw, true); $data = is_array($decoded) ? $decoded : []; return $data; }
function q(string $key, mixed $default = null): mixed { return $_GET[$key] ?? $default; }
function respond(mixed $data, int $status = 200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); exit; }
function fail(string $message, int $status = 422, array $errors = []): never { $payload = ['message' => $message]; if ($errors !== []) $payload['errors'] = $errors; respond($payload, $status); }
function require_fields(array $payload, array $fields): void {
    $errors = [];
    foreach ($fields as $field) { $v = $payload[$field] ?? null; if ($v === null || (is_string($v) && trim($v) === '')) $errors[$field] = ["Field {$field} wajib diisi."]; }
    if ($errors !== []) fail('Data yang dikirim belum lengkap.', 422, $errors);
}
function route_path(): string {
    $uri = $_SERVER['REQUEST_URI'] ?? '/'; $path = parse_url($uri, PHP_URL_PATH) ?: '/';
    if (str_contains($path, 'api-hotel.php')) { $pos = strpos($path, 'api-hotel.php'); $path = substr($path, $pos + strlen('api-hotel.php')); }
    $path = trim($path, '/'); if ($path === '' && isset($_GET['path'])) $path = trim((string) $_GET['path'], '/'); return $path;
}
function match_route(string $pattern, string $path): ?array {
    $a = $pattern === '' ? [] : explode('/', trim($pattern, '/')); $b = $path === '' ? [] : explode('/', trim($path, '/'));
    if (count($a) !== count($b)) return null; $params = [];
    foreach ($a as $i => $part) { $value = $b[$i]; if (preg_match('/^\{(.+)\}$/', $part, $m)) { $params[$m[1]] = $value; continue; } if ($part !== $value) return null; }
    return $params;
}
function env_secret(array $env): string {
    $key = (string) ($env['APP_KEY'] ?? 'hotel-book-secret');
    if (str_starts_with($key, 'base64:')) { $decoded = base64_decode(substr($key, 7), true); if ($decoded !== false) return $decoded; }
    return $key;
}
function issue_token(array $user, string $secret): string {
    $payload = ['id' => $user['id'] ?? null, 'name' => $user['name'] ?? '', 'email' => $user['email'] ?? '', 'role' => $user['role'] ?? '', 'permissions' => array_values($user['permissions'] ?? []), 'issued_at' => time()];
    $encoded = rtrim(strtr(base64_encode(json_encode($payload, JSON_UNESCAPED_UNICODE)), '+/', '-_'), '=');
    return $encoded . '.' . hash_hmac('sha256', $encoded, $secret);
}
function resolve_auth_user(string $secret): ?array {
    $rawToken = $_SERVER['HTTP_X_PMS_TOKEN'] ?? $_SERVER['REDIRECT_HTTP_X_PMS_TOKEN'] ?? '';
    $header = $_SERVER['HTTP_AUTHORIZATION'] ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] ?? $_SERVER['Authorization'] ?? '';
    if ($header === '' && function_exists('getallheaders')) {
        $headers = getallheaders();
        $header = $headers['Authorization'] ?? $headers['authorization'] ?? '';
        $rawToken = $rawToken ?: ($headers['X-PMS-Token'] ?? $headers['x-pms-token'] ?? '');
    }
    if ($header === '' && function_exists('apache_request_headers')) {
        $headers = apache_request_headers();
        $header = $headers['Authorization'] ?? $headers['authorization'] ?? '';
        $rawToken = $rawToken ?: ($headers['X-PMS-Token'] ?? $headers['x-pms-token'] ?? '');
    }
    $token = '';
    if (preg_match('/Bearer\s+(.+)/i', $header, $m)) {
        $token = trim($m[1]);
    } elseif ($rawToken !== '') {
        $token = trim($rawToken);
    }
    if ($token === '') return null;
    $parts = explode('.', $token, 2); if (count($parts) !== 2) return null;
    [$encoded, $signature] = $parts; if (!hash_equals(hash_hmac('sha256', $encoded, $secret), $signature)) return null;
    $decoded = base64_decode(strtr($encoded, '-_', '+/') . str_repeat('=', (4 - strlen($encoded) % 4) % 4), true); if ($decoded === false) return null;
    $payload = json_decode($decoded, true); return is_array($payload) ? $payload : null;
}
function can_access(?array $user, ?string $permission): bool {
    if ($permission === null) return true; if (!$user) return false; if (($user['role'] ?? null) === 'admin') return true;
    return in_array($permission, is_array($user['permissions'] ?? null) ? $user['permissions'] : [], true);
}
function db_one(PDO $db, string $sql, array $params = []): ?array { $stmt = $db->prepare($sql); $stmt->execute($params); $row = $stmt->fetch(PDO::FETCH_ASSOC); return $row === false ? null : $row; }
function db_all(PDO $db, string $sql, array $params = []): array { $stmt = $db->prepare($sql); $stmt->execute($params); return $stmt->fetchAll(PDO::FETCH_ASSOC); }
function db_value(PDO $db, string $sql, array $params = []): mixed { $stmt = $db->prepare($sql); $stmt->execute($params); return $stmt->fetchColumn(); }
function paginate_meta(int $page, int $perPage, int $total): array { return ['current_page' => $page, 'last_page' => max(1, (int) ceil($total / max(1, $perPage))), 'per_page' => $perPage, 'total' => $total]; }

function ensure_runtime_schema(PDO $db): void {
    static $done = false; if ($done) return;
    $db->exec("CREATE TABLE IF NOT EXISTS audit_trails (
        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        user_id BIGINT UNSIGNED NULL, user_name VARCHAR(150) NULL, user_email VARCHAR(150) NULL, user_role VARCHAR(100) NULL,
        module VARCHAR(80) NOT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(120) NULL, entity_id VARCHAR(120) NULL, entity_label VARCHAR(191) NULL,
        description TEXT NOT NULL, metadata LONGTEXT NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(255) NULL,
        created_at TIMESTAMP NULL DEFAULT NULL, updated_at TIMESTAMP NULL DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $columns = []; foreach ($db->query("SHOW COLUMNS FROM roles") as $row) $columns[$row['Field']] = true;
    if (!isset($columns['permissions'])) $db->exec("ALTER TABLE roles ADD COLUMN permissions LONGTEXT NULL");
    $exists = function (string $table) use ($db): bool { $stmt = $db->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?"); $stmt->execute([$table]); return (int) $stmt->fetchColumn() > 0; };
    if (!$exists('transport_rates')) $db->exec("CREATE TABLE transport_rates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, driver VARCHAR(255) NOT NULL, pickup_price_value DECIMAL(15,2) NOT NULL DEFAULT 0, drop_off_price_value DECIMAL(15,2) NOT NULL DEFAULT 0, vehicle VARCHAR(255) NULL, note TEXT NULL, created_at TIMESTAMP NULL DEFAULT NULL, updated_at TIMESTAMP NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if (!$exists('activity_operator_catalog')) $db->exec("CREATE TABLE activity_operator_catalog (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, operator VARCHAR(255) NOT NULL, price_value DECIMAL(15,2) NOT NULL DEFAULT 0, note TEXT NULL, created_at TIMESTAMP NULL DEFAULT NULL, updated_at TIMESTAMP NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if (!$exists('island_tour_catalog')) $db->exec("CREATE TABLE island_tour_catalog (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, destination VARCHAR(255) NOT NULL, driver VARCHAR(255) NOT NULL, cost_value DECIMAL(15,2) NOT NULL DEFAULT 0, note TEXT NULL, created_at TIMESTAMP NULL DEFAULT NULL, updated_at TIMESTAMP NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if (!$exists('boat_ticket_catalog')) $db->exec("CREATE TABLE boat_ticket_catalog (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company VARCHAR(255) NOT NULL, destination VARCHAR(255) NOT NULL, price_value DECIMAL(15,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NULL DEFAULT NULL, updated_at TIMESTAMP NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if ($exists('scooter_catalog')) {
        $cols = []; foreach ($db->query("SHOW COLUMNS FROM scooter_catalog") as $row) $cols[$row['Field']] = true;
        if (!isset($cols['start_date'])) $db->exec("ALTER TABLE scooter_catalog ADD COLUMN start_date DATE NULL");
        if (!isset($cols['end_date'])) $db->exec("ALTER TABLE scooter_catalog ADD COLUMN end_date DATE NULL");
        if (!isset($cols['vendor'])) $db->exec("ALTER TABLE scooter_catalog ADD COLUMN vendor VARCHAR(255) NULL");
        if (!isset($cols['price_value'])) $db->exec("ALTER TABLE scooter_catalog ADD COLUMN price_value DECIMAL(15,2) NOT NULL DEFAULT 0");
    }
    $done = true;
}
function audit_log(PDO $db, array $entry, ?array $actor): void {
    ensure_runtime_schema($db); $stmt = $db->prepare("INSERT INTO audit_trails (user_id,user_name,user_email,user_role,module,action,entity_type,entity_id,entity_label,description,metadata,ip_address,user_agent,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); $now = now_ts();
    $stmt->execute([$actor['id'] ?? null, $actor['name'] ?? null, $actor['email'] ?? null, $actor['role'] ?? null, (string) ($entry['module'] ?? 'system'), (string) ($entry['action'] ?? 'updated'), $entry['entity_type'] ?? null, isset($entry['entity_id']) ? (string) $entry['entity_id'] : null, $entry['entity_label'] ?? null, (string) ($entry['description'] ?? ''), isset($entry['metadata']) ? json_encode($entry['metadata'], JSON_UNESCAPED_UNICODE) : null, $_SERVER['REMOTE_ADDR'] ?? null, isset($_SERVER['HTTP_USER_AGENT']) ? substr((string) $_SERVER['HTTP_USER_AGENT'], 0, 255) : null, $now, $now]);
}

function normalize_source(string $value): string { return match (strtolower(trim($value))) { 'direct' => 'direct', 'airbnb' => 'airbnb', 'booking.com' => 'booking.com', 'agoda', 'booking' => 'agoda', 'traveloka' => 'traveloka', 'walk-in', 'walk_in', 'walkin' => 'walk_in', default => 'other', }; }
function source_label(string $value): string { return match ($value) { 'direct' => 'Direct', 'airbnb' => 'Airbnb', 'booking.com' => 'Booking.com', 'agoda' => 'Booking', 'traveloka' => 'Traveloka', 'walk_in' => 'Walk-in', default => 'Other', }; }
function normalize_booking_status(string $value): string { return match (strtolower(trim($value))) { 'tentative', 'draft' => 'draft', 'confirmed' => 'confirmed', 'checked-in', 'checked_in' => 'checked_in', 'checked-out', 'checked_out', 'completed' => 'checked_out', 'cancelled', 'canceled' => 'cancelled', 'no-show', 'no_show' => 'no_show', default => 'confirmed', }; }
function booking_status_label(string $value): string { return match ($value) { 'draft' => 'Tentative', 'confirmed' => 'Confirmed', 'checked_in' => 'Checked-in', 'checked_out' => 'Checked-out', 'cancelled' => 'Cancelled', 'no_show' => 'No-Show', default => ucfirst($value), }; }
function normalize_addon_status(string $value): string { return match (strtolower(trim($value))) { 'planned' => 'planned', 'confirmed' => 'confirmed', 'posted', 'completed' => 'completed', 'cancelled' => 'cancelled', default => 'planned', }; }
function addon_status_label(string $value): string { return match ($value) { 'planned' => 'Planned', 'confirmed' => 'Confirmed', 'completed' => 'Posted', 'cancelled' => 'Cancelled', default => ucfirst(str_replace('_', ' ', $value)), }; }
function normalize_payment_method(string $value): string { return match (strtolower(trim($value))) { 'cash', 'tunai' => 'cash', 'bank transfer', 'bank_transfer', 'transfer' => 'bank_transfer', 'credit card', 'credit_card' => 'credit_card', 'debit card', 'debit_card' => 'debit_card', 'qris' => 'qris', default => 'other', }; }

function guest_upsert(PDO $db, ?int $guestId, array $payload): int {
    $now = now_ts();
    if ($guestId) { $db->prepare("UPDATE guests SET full_name=?, phone=?, email=?, notes=?, updated_at=? WHERE id=?")->execute([trim((string) $payload['guest']), trim((string) ($payload['phone'] ?? '')) ?: null, trim((string) ($payload['email'] ?? '')) ?: null, trim((string) ($payload['note'] ?? '')) ?: null, $now, $guestId]); return $guestId; }
    $guestCode = 'GST-' . date('ymdHis') . '-' . random_int(10, 99);
    $db->prepare("INSERT INTO guests (guest_code, full_name, email, phone, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)")->execute([$guestCode, trim((string) $payload['guest']), trim((string) ($payload['email'] ?? '')) ?: null, trim((string) ($payload['phone'] ?? '')) ?: null, trim((string) ($payload['note'] ?? '')) ?: null, $now, $now]);
    return (int) $db->lastInsertId();
}
function calculate_room_amount(array $roomDetails, string $checkIn, string $checkOut): float { $nights = max(1, (int) floor((strtotime($checkOut) - strtotime($checkIn)) / 86400)); $total = 0.0; foreach ($roomDetails as $detail) $total += as_float($detail['rate'] ?? 0) * $nights; return $total; }
function generate_booking_code(PDO $db, string $checkIn): string { $prefix = 'BK-' . date('ymd', strtotime($checkIn)); $last = (string) db_value($db, "SELECT booking_code FROM bookings WHERE booking_code LIKE ? ORDER BY id DESC LIMIT 1", [$prefix . '-%']); return sprintf('%s-%03d', $prefix, ($last !== '' ? (int) substr($last, -3) : 0) + 1); }
function generate_payment_code(PDO $db): string { $prefix = 'PAY-' . date('ymd'); $last = (string) db_value($db, "SELECT payment_number FROM payments WHERE payment_number LIKE ? ORDER BY id DESC LIMIT 1", [$prefix . '-%']); return sprintf('%s-%03d', $prefix, ($last !== '' ? (int) substr($last, -3) : 0) + 1); }
function generate_journal_number(PDO $db, string $journalDate): string { $count = (int) db_value($db, "SELECT COUNT(*) FROM journals WHERE journal_date = ?", [$journalDate]) + 1; return sprintf('JU-%s-%03d', str_replace('-', '', $journalDate), $count); }
function resolve_revenue_coa(PDO $db, array $preferredCodes, string $prefix): string {
    foreach ($preferredCodes as $code) if ((int) db_value($db, "SELECT COUNT(*) FROM coa_accounts WHERE code = ?", [$code]) > 0) return $code;
    $fallback = db_value($db, "SELECT code FROM coa_accounts WHERE LOWER(category) = 'revenue' AND code LIKE ? ORDER BY code ASC LIMIT 1", [$prefix . '%']); if ($fallback) return (string) $fallback;
    $fallback = db_value($db, "SELECT code FROM coa_accounts WHERE LOWER(category) = 'revenue' ORDER BY code ASC LIMIT 1"); return (string) ($fallback ?: $preferredCodes[0]);
}
function resolve_room_revenue_coa(PDO $db, string $source): string { $preferred = match ($source) { 'airbnb' => '411018', 'booking.com' => '411023', default => '411021', }; return resolve_revenue_coa($db, [$preferred, '411021', '411018', '411023'], '411'); }
function resolve_addon_revenue_coa(PDO $db, string $addonType): string { $preferred = match ($addonType) { 'transport' => '510001', 'scooter' => '510002', 'boat_ticket' => '510004', 'island_tour' => '510005', default => '411021', }; return resolve_revenue_coa($db, [$preferred, '411021', '510001'], str_starts_with($preferred, '510') ? '510' : '411'); }
function resolve_cash_bank_coa(PDO $db, string $method): string { $preferred = normalize_payment_method($method) === 'cash' ? '111001' : '111005'; if ((int) db_value($db, "SELECT COUNT(*) FROM coa_accounts WHERE code = ?", [$preferred]) > 0) return $preferred; $fallback = db_value($db, "SELECT code FROM coa_accounts WHERE LOWER(category) = 'asset' AND code LIKE '111%' ORDER BY code ASC LIMIT 1"); return (string) ($fallback ?: '111001'); }
function resolve_receivable_coa(PDO $db): string { if ((int) db_value($db, "SELECT COUNT(*) FROM coa_accounts WHERE code = '112001'") > 0) return '112001'; $fallback = db_value($db, "SELECT code FROM coa_accounts WHERE LOWER(category) = 'asset' AND code LIKE '112%' ORDER BY code ASC LIMIT 1"); return (string) ($fallback ?: '112001'); }
function room_details_for_booking(PDO $db, int $bookingId): array {
    $rows = db_all($db, "SELECT br.*, r.room_code, rt.name AS room_type_name FROM booking_rooms br JOIN rooms r ON r.id = br.room_id JOIN room_types rt ON rt.id = r.room_type_id WHERE br.booking_id = ? ORDER BY r.room_code ASC", [$bookingId]);
    return array_map(static fn (array $row): array => ['room' => $row['room_code'], 'roomType' => $row['room_type_name'], 'rate' => as_float($row['rate']), 'adults' => as_int($row['adult_count']), 'children' => as_int($row['child_count'])], $rows);
}
function addon_rows_for_booking(PDO $db, int $bookingId): array {
    $rows = db_all($db, "SELECT * FROM booking_addons WHERE booking_id = ? ORDER BY id ASC", [$bookingId]);
    return array_map(static function (array $row): array {
        $meta = json_decode((string) ($row['notes'] ?? ''), true); $meta = is_array($meta) ? $meta : ['note' => (string) ($row['notes'] ?? '')];
        $serviceDate = $row['service_date'] ?: ($row['start_date'] ?: null); $startDate = $row['start_date'] ?: null; $endDate = $row['end_date'] ?: null;
        return ['id' => as_int($row['id']), 'addonType' => $row['addon_type'], 'addonLabel' => $meta['addonLabel'] ?? ucfirst(str_replace('_', ' ', (string) $row['addon_type'])), 'serviceName' => $meta['serviceName'] ?? 'Add-on service', 'itemRef' => $meta['itemRef'] ?? '', 'serviceDate' => $serviceDate, 'startDate' => $startDate, 'endDate' => $endDate, 'serviceDateLabel' => $row['addon_type'] === 'scooter' && $startDate && $endDate ? "{$startDate} to {$endDate}" : $serviceDate, 'quantity' => as_int($row['qty']), 'unitPriceValue' => as_float($row['unit_price']), 'unitPrice' => money(as_float($row['unit_price'])), 'totalPriceValue' => as_float($row['total_price']), 'totalPrice' => money(as_float($row['total_price'])), 'status' => addon_status_label((string) $row['status']), 'notes' => $meta['note'] ?? ''];
    }, $rows);
}
function transform_booking(PDO $db, array $booking): array {
    $roomDetails = room_details_for_booking($db, as_int($booking['id'])); $addons = addon_rows_for_booking($db, as_int($booking['id'])); $invoice = db_one($db, "SELECT * FROM invoices WHERE booking_id = ? LIMIT 1", [$booking['id']]); $rooms = array_values(array_filter(array_map(static fn (array $row): ?string => $row['room'] ?: null, $roomDetails)));
    return ['code' => $booking['booking_code'], 'guest' => $booking['guest_name'] ?? '', 'phone' => $booking['guest_phone'] ?? '', 'email' => $booking['guest_email'] ?? '', 'checkIn' => date('Y-m-d H:i', strtotime((string) $booking['check_in_at'])), 'checkOut' => date('Y-m-d H:i', strtotime((string) $booking['check_out_at'])), 'channel' => source_label((string) $booking['source']), 'status' => booking_status_label((string) $booking['status']), 'note' => $booking['notes'] ?? '', 'roomDetails' => $roomDetails, 'rooms' => $rooms, 'room' => implode(', ', $rooms), 'roomType' => implode(', ', array_values(array_unique(array_filter(array_map(static fn (array $row): ?string => $row['roomType'] ?: null, $roomDetails))))), 'roomCount' => count($roomDetails), 'adults' => array_sum(array_map(static fn (array $row): int => as_int($row['adults']), $roomDetails)), 'children' => array_sum(array_map(static fn (array $row): int => as_int($row['children']), $roomDetails)), 'amountValue' => as_float($booking['room_amount']), 'amount' => money(as_float($booking['room_amount'])), 'addons' => $addons, 'addonsTotalValue' => as_float($booking['addon_amount']), 'addonsTotal' => money(as_float($booking['addon_amount'])), 'grandTotalValue' => as_float($booking['grand_total']), 'grandTotal' => money(as_float($booking['grand_total'])), 'invoiceNo' => $invoice['invoice_number'] ?? ('INV-' . str_replace('BK-', '', (string) $booking['booking_code'])), 'issueDate' => $invoice['invoice_date'] ?? date('Y-m-d', strtotime((string) $booking['check_in_at'])), 'dueDate' => $invoice['due_date'] ?? date('Y-m-d', strtotime((string) $booking['check_out_at'])), 'paidAmountValue' => as_float($invoice['paid_amount'] ?? 0), 'paidAmount' => money(as_float($invoice['paid_amount'] ?? 0)), 'balanceValue' => as_float($invoice['balance_due'] ?? $booking['grand_total']), 'balanceAmount' => money(as_float($invoice['balance_due'] ?? $booking['grand_total'])), 'invoiceStatus' => ucfirst((string) ($invoice['status'] ?? 'draft'))];
}
function load_booking_row(PDO $db, string $bookingCode): ?array { return db_one($db, "SELECT b.*, g.full_name AS guest_name, g.phone AS guest_phone, g.email AS guest_email FROM bookings b JOIN guests g ON g.id = b.guest_id WHERE b.booking_code = ? LIMIT 1", [$bookingCode]); }
function sync_booking_rooms(PDO $db, int $bookingId, array $roomDetails, string $checkIn, string $checkOut): void {
    $db->prepare("DELETE FROM booking_rooms WHERE booking_id = ?")->execute([$bookingId]); $lookup = $db->prepare("SELECT id FROM rooms WHERE room_code = ? LIMIT 1");
    $insert = $db->prepare("INSERT INTO booking_rooms (booking_id, room_id, adult_count, child_count, rate, check_in_at, check_out_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"); $now = now_ts();
    foreach ($roomDetails as $detail) { $lookup->execute([trim((string) ($detail['room'] ?? ''))]); $roomId = $lookup->fetchColumn(); if (!$roomId) fail("Kamar {$detail['room']} tidak ditemukan."); $insert->execute([$bookingId, $roomId, max(1, as_int($detail['adults'] ?? 1)), max(0, as_int($detail['children'] ?? 0)), as_float($detail['rate'] ?? 0), $checkIn, $checkOut, $now, $now]); }
}
function ensure_rooms_available(PDO $db, array $roomDetails, string $checkIn, string $checkOut, ?int $ignoreBookingId = null): void {
    $seen = [];
    foreach ($roomDetails as $detail) {
        $roomCode = trim((string) ($detail['room'] ?? '')); if ($roomCode === '') fail('Data kamar belum lengkap.', 422, ['roomDetails' => ['Kode kamar wajib diisi.']]); if (isset($seen[$roomCode])) fail('Satu kamar tidak boleh dipilih lebih dari sekali.', 422, ['roomDetails' => ['Satu kamar tidak boleh dipilih lebih dari sekali.']]); $seen[$roomCode] = true;
        $room = db_one($db, "SELECT id FROM rooms WHERE room_code = ? LIMIT 1", [$roomCode]); if (!$room) fail("Kamar {$roomCode} tidak ditemukan.", 422, ['roomDetails' => ["Kamar {$roomCode} tidak ditemukan."]]);
        $params = [$room['id'], $checkOut, $checkIn]; $sql = "SELECT COUNT(*) FROM booking_rooms br JOIN bookings b ON b.id = br.booking_id WHERE br.room_id = ? AND b.status NOT IN ('cancelled', 'no_show') AND b.check_in_at < ? AND b.check_out_at > ?";
        if ($ignoreBookingId !== null) { $sql .= " AND b.id != ?"; $params[] = $ignoreBookingId; }
        if ((int) db_value($db, $sql, $params) > 0) fail("Kamar {$roomCode} sudah terpakai pada rentang tanggal tersebut.", 422, ['roomDetails' => ["Kamar {$roomCode} sudah terpakai pada rentang tanggal tersebut."]]);
    }
}
function upsert_booking_invoice_journal(PDO $db, int $bookingId, ?int $invoiceId): void {
    if (!$invoiceId) return; $booking = db_one($db, "SELECT * FROM bookings WHERE id = ?", [$bookingId]); $invoice = db_one($db, "SELECT * FROM invoices WHERE id = ?", [$invoiceId]); if (!$booking || !$invoice) return;
    $roomRevenue = as_float($booking['room_amount']); $receivableTotal = as_float($invoice['grand_total']); $addonRevenueRows = db_all($db, "SELECT addon_type, SUM(total_price) AS total_price FROM booking_addons WHERE booking_id = ? AND status != 'cancelled' GROUP BY addon_type", [$bookingId]);
    $journal = db_one($db, "SELECT * FROM journals WHERE source = 'invoice' AND reference_type = 'booking' AND reference_id = ? LIMIT 1", [$bookingId]); $journalDate = $invoice['invoice_date'] ?: today_date();
    if ($journal) { $journalId = as_int($journal['id']); $db->prepare("UPDATE journals SET journal_date = ?, description = ?, updated_at = ? WHERE id = ?")->execute([$journalDate, "Invoice {$invoice['invoice_number']} for {$booking['booking_code']}", now_ts(), $journalId]); $db->prepare("DELETE FROM journal_lines WHERE journal_id = ?")->execute([$journalId]); }
    else { $db->prepare("INSERT INTO journals (journal_number, journal_date, reference_type, reference_id, description, source, posted_by, created_at, updated_at) VALUES (?, ?, 'booking', ?, ?, 'invoice', NULL, ?, ?)")->execute([generate_journal_number($db, $journalDate), $journalDate, $bookingId, "Invoice {$invoice['invoice_number']} for {$booking['booking_code']}", now_ts(), now_ts()]); $journalId = (int) $db->lastInsertId(); }
    $insert = $db->prepare("INSERT INTO journal_lines (journal_id, coa_code, line_description, debit, credit, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)"); $now = now_ts();
    $insert->execute([$journalId, resolve_receivable_coa($db), "Accounts receivable {$invoice['invoice_number']}", $receivableTotal, 0, $now, $now]);
    if ($roomRevenue > 0) $insert->execute([$journalId, resolve_room_revenue_coa($db, (string) $booking['source']), "Room revenue {$booking['booking_code']}", 0, $roomRevenue, $now, $now]);
    foreach ($addonRevenueRows as $row) { $value = as_float($row['total_price']); if ($value <= 0) continue; $insert->execute([$journalId, resolve_addon_revenue_coa($db, (string) $row['addon_type']), "Add-on revenue {$booking['booking_code']} ({$row['addon_type']})", 0, $value, $now, $now]); }
}
function sync_booking_financial_state(PDO $db, int $bookingId): void {
    $booking = db_one($db, "SELECT * FROM bookings WHERE id = ?", [$bookingId]); if (!$booking) return; $addonTotal = as_float(db_value($db, "SELECT COALESCE(SUM(total_price), 0) FROM booking_addons WHERE booking_id = ? AND status != 'cancelled'", [$bookingId])); $grandTotal = as_float($booking['room_amount']) + $addonTotal - as_float($booking['discount_amount']) + as_float($booking['tax_amount']);
    $db->prepare("UPDATE bookings SET addon_amount = ?, grand_total = ?, updated_at = ? WHERE id = ?")->execute([$addonTotal, $grandTotal, now_ts(), $bookingId]); $invoice = db_one($db, "SELECT * FROM invoices WHERE booking_id = ? LIMIT 1", [$bookingId]);
    if ($invoice) { $paidAmount = as_float($invoice['paid_amount']); $balance = max(0, $grandTotal - $paidAmount); $status = $balance <= 0 ? 'paid' : ($paidAmount > 0 ? 'partial' : 'unpaid'); $db->prepare("UPDATE invoices SET due_date = ?, subtotal = ?, grand_total = ?, balance_due = ?, status = ?, updated_at = ? WHERE id = ?")->execute([date('Y-m-d', strtotime((string) $booking['check_out_at'])), as_float($booking['room_amount']), $grandTotal, $balance, $status, now_ts(), $invoice['id']]); $invoice['id'] = $invoice['id']; }
    else { $db->prepare("INSERT INTO invoices (booking_id, invoice_number, invoice_date, due_date, subtotal, discount_amount, tax_amount, grand_total, paid_amount, balance_due, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, ?, 'unpaid', ?, ?)")->execute([$bookingId, 'INV-' . str_replace('BK-', '', (string) $booking['booking_code']), today_date(), date('Y-m-d', strtotime((string) $booking['check_out_at'])), as_float($booking['room_amount']), as_float($booking['discount_amount']), as_float($booking['tax_amount']), $grandTotal, $grandTotal, now_ts(), now_ts()]); $invoice = db_one($db, "SELECT * FROM invoices WHERE booking_id = ? LIMIT 1", [$bookingId]); }
    upsert_booking_invoice_journal($db, $bookingId, $invoice ? as_int($invoice['id']) : null);
}
function sync_payment_accounting(PDO $db, int $paymentId): void {
    $payment = db_one($db, "SELECT * FROM payments WHERE id = ?", [$paymentId]); if (!$payment) return; $allocation = db_one($db, "SELECT * FROM payment_allocations WHERE payment_id = ? LIMIT 1", [$paymentId]); if (!$allocation) return; $invoice = db_one($db, "SELECT * FROM invoices WHERE id = ?", [$allocation['invoice_id']]); if (!$invoice) return;
    $cashBank = $payment['cash_bank_coa_code'] ?: resolve_cash_bank_coa($db, (string) $payment['payment_method']); if ($cashBank !== $payment['cash_bank_coa_code']) $db->prepare("UPDATE payments SET cash_bank_coa_code = ?, updated_at = ? WHERE id = ?")->execute([$cashBank, now_ts(), $paymentId]);
    $journal = db_one($db, "SELECT * FROM journals WHERE source = 'payment' AND reference_type = 'payment' AND reference_id = ? LIMIT 1", [$paymentId]); $journalDate = $payment['payment_date'];
    if ($journal) { $journalId = as_int($journal['id']); $db->prepare("UPDATE journals SET journal_date = ?, description = ?, updated_at = ? WHERE id = ?")->execute([$journalDate, "Guest payment {$payment['payment_number']} for {$invoice['invoice_number']}", now_ts(), $journalId]); $db->prepare("DELETE FROM journal_lines WHERE journal_id = ?")->execute([$journalId]); }
    else { $db->prepare("INSERT INTO journals (journal_number, journal_date, reference_type, reference_id, description, source, posted_by, created_at, updated_at) VALUES (?, ?, 'payment', ?, ?, 'payment', NULL, ?, ?)")->execute([generate_journal_number($db, (string) $journalDate), $journalDate, $paymentId, "Guest payment {$payment['payment_number']} for {$invoice['invoice_number']}", now_ts(), now_ts()]); $journalId = (int) $db->lastInsertId(); }
    $insert = $db->prepare("INSERT INTO journal_lines (journal_id, coa_code, line_description, debit, credit, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)"); $amount = as_float($payment['amount']); $now = now_ts();
    $insert->execute([$journalId, $cashBank, "Cash receipt {$payment['payment_number']}", $amount, 0, $now, $now]); $insert->execute([$journalId, resolve_receivable_coa($db), "Settlement invoice {$invoice['invoice_number']}", 0, $amount, $now, $now]);
}
function payment_transform(PDO $db, array $payment): array {
    $allocation = db_one($db, "SELECT * FROM payment_allocations WHERE payment_id = ? LIMIT 1", [$payment['id']]); $invoice = $allocation ? db_one($db, "SELECT * FROM invoices WHERE id = ?", [$allocation['invoice_id']]) : null; $booking = $invoice ? db_one($db, "SELECT booking_code FROM bookings WHERE id = ?", [$invoice['booking_id']]) : null;
    return ['id' => as_int($payment['id']), 'paymentNumber' => $payment['payment_number'], 'bookingCode' => $booking['booking_code'] ?? '', 'invoiceNo' => $invoice['invoice_number'] ?? '', 'paymentDate' => $payment['payment_date'], 'method' => ucfirst(str_replace('_', ' ', (string) $payment['payment_method'])), 'referenceNo' => $payment['reference_number'], 'amountValue' => as_float($payment['amount']), 'amount' => money(as_float($payment['amount'])), 'note' => $payment['notes'] ?? ''];
}

$baseDir = __DIR__; $env = env_map($baseDir . DIRECTORY_SEPARATOR . 'backend' . DIRECTORY_SEPARATOR . '.env');
$dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4', $env['DB_HOST'] ?? '127.0.0.1', $env['DB_PORT'] ?? '3306', $env['DB_DATABASE'] ?? 'hotel');
try { $db = new PDO($dsn, $env['DB_USERNAME'] ?? 'root', $env['DB_PASSWORD'] ?? '', [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]); }
catch (Throwable $e) { fail('Gagal terhubung ke database MySQL.', 500); }
ensure_runtime_schema($db); $secret = env_secret($env); $method = strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')); $path = route_path(); $actor = null;
$permissionRoutes = [
    ['GET', 'coa-accounts', 'coa'], ['POST', 'coa-accounts', 'coa'], ['PUT', 'coa-accounts/{code}', 'coa'], ['GET', 'room-types', 'rooms'], ['GET', 'rooms', 'rooms'], ['POST', 'rooms', 'rooms'], ['PUT', 'rooms/{code}', 'rooms'],
    ['GET', 'bookings', 'bookings'], ['GET', 'bookings/{code}', 'bookings'], ['POST', 'bookings', 'bookings'], ['PUT', 'bookings/{code}', 'bookings'], ['PATCH', 'bookings/{code}/status', 'bookings'], ['POST', 'bookings/{code}/addons', 'bookings'], ['PATCH', 'bookings/{code}/addons/{id}', 'bookings'], ['DELETE', 'bookings/{code}/addons/{id}', 'bookings'],
    ['GET', 'journals', 'journals'], ['POST', 'journals', 'journals'], ['PUT', 'journals/{id}', 'journals'], ['GET', 'payments', 'finance'], ['POST', 'payments', 'finance'], ['GET', 'inventory', 'inventory'], ['POST', 'inventory/items', 'inventory'], ['POST', 'inventory/purchases', 'inventory'], ['POST', 'inventory/issues', 'inventory'],
    ['GET', 'transport-rates', 'transport'], ['POST', 'transport-rates', 'transport'], ['PUT', 'transport-rates/{id}', 'transport'], ['GET', 'activity-catalog', 'activities'], ['POST', 'activity-catalog/scooters', 'activities'], ['PUT', 'activity-catalog/scooters/{id}', 'activities'], ['POST', 'activity-catalog/operators', 'activities'], ['PUT', 'activity-catalog/operators/{id}', 'activities'], ['POST', 'activity-catalog/island-tours', 'activities'], ['PUT', 'activity-catalog/island-tours/{id}', 'activities'], ['POST', 'activity-catalog/boat-tickets', 'activities'], ['PUT', 'activity-catalog/boat-tickets/{id}', 'activities'],
    ['GET', 'reports/balance-sheet', 'reports'], ['GET', 'reports/profit-loss', 'reports'], ['GET', 'reports/cash-flow', 'reports'], ['GET', 'reports/reconciliation', 'reports'], ['GET', 'audit-trails', 'reports'], ['GET', 'dashboard/owner', 'dashboard'], ['GET', 'night-audit/status', 'dashboard'], ['POST', 'night-audit', 'roles'], ['POST', 'accounting/sync-history', 'roles'],
    ['GET', 'roles', 'roles'], ['PUT', 'roles/{id}/permissions', 'roles'], ['GET', 'users', 'users'], ['POST', 'users', 'users'], ['PUT', 'users/{id}', 'users'], ['PATCH', 'users/{id}/toggle', 'users'],
];
if (!($method === 'POST' && $path === 'login')) {
    $actor = resolve_auth_user($secret); if (!$actor) fail('Sesi login tidak valid atau telah berakhir.', 401);
    foreach ($permissionRoutes as [$rm, $rp, $perm]) if ($rm === $method && match_route($rp, $path) !== null && !can_access($actor, $perm)) fail('Anda tidak memiliki akses ke modul ini.', 403);
}
try {
    if ($method === 'POST' && $path === 'login') {
        $payload = json_input(); require_fields($payload, ['email', 'password']);
        $userRecord = db_one($db, "SELECT u.id, u.name, u.email, u.password, u.is_active, r.name AS role, r.permissions FROM users u LEFT JOIN roles r ON r.id = u.role_id WHERE u.email = ? LIMIT 1", [trim((string) $payload['email'])]);
        if ($userRecord && password_verify((string) $payload['password'], (string) $userRecord['password'])) {
            if (!as_int($userRecord['is_active'])) fail('Akun Anda dinonaktifkan.', 403);
            $user = ['id' => as_int($userRecord['id']), 'name' => $userRecord['name'], 'email' => $userRecord['email'], 'role' => $userRecord['role'] ?: 'frontdesk', 'permissions' => $userRecord['permissions'] ? (json_decode((string) $userRecord['permissions'], true) ?: []) : []];
            audit_log($db, ['module' => 'auth', 'action' => 'login', 'entity_type' => 'user', 'entity_id' => $user['id'], 'entity_label' => $user['email'], 'description' => "User {$user['email']} berhasil login.", 'metadata' => ['permissions' => $user['permissions'], 'source' => 'database']], $user);
            respond(['token' => issue_token($user, $secret), 'user' => $user]);
        }
        $demo = ['admin@sagarabay.com' => ['General Manager (Demo)', 'admin123', 'admin', ['dashboard', 'bookings', 'rooms', 'finance', 'journals', 'coa', 'inventory', 'transport', 'activities', 'reports', 'users', 'roles'], 991], 'fo@sagarabay.com' => ['Resepsionis (Demo)', 'fo123', 'frontdesk', ['dashboard', 'bookings', 'rooms', 'activities'], 992], 'hk@sagarabay.com' => ['Housekeeping (Demo)', 'hk123', 'housekeeping', ['rooms', 'inventory'], 993]];
        $email = trim((string) $payload['email']);
        if (isset($demo[$email]) && $demo[$email][1] === (string) $payload['password']) { [$name, , $role, $permissions, $id] = $demo[$email]; $user = compact('id', 'name', 'email', 'role', 'permissions'); audit_log($db, ['module' => 'auth', 'action' => 'login', 'entity_type' => 'user', 'entity_id' => $id, 'entity_label' => $email, 'description' => "User demo {$email} berhasil login.", 'metadata' => ['permissions' => $permissions, 'source' => 'demo']], $user); respond(['token' => issue_token($user, $secret), 'user' => $user]); }
        fail('Email atau Password salah.', 401);
    }

    if ($method === 'GET' && $path === 'coa-accounts') {
        $page = max(1, as_int(q('page', 1))); $perPage = min(max(as_int(q('per_page', 15)), 1), 100); $search = trim((string) q('search', '')); $category = strtolower(trim((string) q('category', '')));
        $where = []; $params = [];
        if ($search !== '') { $like = '%' . $search . '%'; $where[] = "(code LIKE ? OR account_name LIKE ? OR note LIKE ?)"; array_push($params, $like, $like, $like); }
        if ($category !== '') { $where[] = "category = ?"; $params[] = $category; }
        $whereSql = $where ? 'WHERE ' . implode(' AND ', $where) : ''; $total = (int) db_value($db, "SELECT COUNT(*) FROM coa_accounts {$whereSql}", $params);
        $rows = db_all($db, "SELECT * FROM coa_accounts {$whereSql} ORDER BY code ASC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage), $params);
        respond(['data' => array_map(static fn (array $row): array => ['code' => $row['code'], 'name' => $row['account_name'], 'category' => ucfirst((string) $row['category']), 'normalBalance' => ucfirst((string) $row['normal_balance']), 'note' => $row['note'] ?? '', 'active' => (bool) as_int($row['is_active'])], $rows), 'meta' => paginate_meta($page, $perPage, $total)]);
    }
    if ($method === 'POST' && $path === 'coa-accounts') {
        $payload = json_input(); require_fields($payload, ['code', 'name', 'category', 'normalBalance']); $code = trim((string) $payload['code']);
        if (db_one($db, "SELECT code FROM coa_accounts WHERE code = ?", [$code])) fail('Kode COA sudah ada.', 422, ['code' => ['Kode COA sudah ada.']]);
        $db->prepare("INSERT INTO coa_accounts (code, account_name, category, normal_balance, note, is_active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)")->execute([$code, trim((string) $payload['name']), strtolower(trim((string) $payload['category'])), strtolower(trim((string) $payload['normalBalance'])), trim((string) ($payload['note'] ?? '')) ?: null, !isset($payload['active']) || $payload['active'] ? 1 : 0, now_ts(), now_ts()]);
        respond(['data' => ['code' => $code, 'name' => trim((string) $payload['name']), 'category' => ucfirst(strtolower(trim((string) $payload['category']))), 'normalBalance' => ucfirst(strtolower(trim((string) $payload['normalBalance']))), 'note' => trim((string) ($payload['note'] ?? '')), 'active' => !isset($payload['active']) || (bool) $payload['active']], 'message' => 'COA berhasil ditambahkan.'], 201);
    }
    if ($method === 'PUT' && ($params = match_route('coa-accounts/{code}', $path)) !== null) {
        $payload = json_input(); require_fields($payload, ['name', 'category', 'normalBalance']);
        $db->prepare("UPDATE coa_accounts SET account_name=?, category=?, normal_balance=?, note=?, is_active=?, updated_at=? WHERE code=?")->execute([trim((string) $payload['name']), strtolower(trim((string) $payload['category'])), strtolower(trim((string) $payload['normalBalance'])), trim((string) ($payload['note'] ?? '')) ?: null, !isset($payload['active']) || $payload['active'] ? 1 : 0, now_ts(), $params['code']]);
        respond(['message' => 'COA berhasil diperbarui.']);
    }

    if ($method === 'GET' && $path === 'room-types') { $rows = db_all($db, "SELECT * FROM room_types ORDER BY name ASC"); respond(['data' => array_map(static fn (array $row): array => ['id' => as_int($row['id']), 'code' => $row['code'], 'name' => $row['name'], 'capacity' => as_int($row['capacity']), 'baseRate' => as_float($row['base_rate'])], $rows)]); }
    if ($method === 'GET' && $path === 'rooms') {
        $page = max(1, as_int(q('page', 1))); $perPage = min(max(as_int(q('per_page', 12)), 1), 100); $search = trim((string) q('search', '')); $where = ''; $params = [];
        if ($search !== '') { $like = '%' . $search . '%'; $where = "WHERE (r.room_code LIKE ? OR r.room_name LIKE ? OR rt.name LIKE ? OR r.coa_receivable_code LIKE ? OR r.coa_revenue_code LIKE ?)"; $params = [$like, $like, $like, $like, $like]; }
        $total = (int) db_value($db, "SELECT COUNT(*) FROM rooms r JOIN room_types rt ON rt.id = r.room_type_id {$where}", $params);
        $rows = db_all($db, "SELECT r.*, rt.name AS room_type_name, rt.base_rate, ar.account_name AS receivable_name, rv.account_name AS revenue_name FROM rooms r JOIN room_types rt ON rt.id = r.room_type_id LEFT JOIN coa_accounts ar ON ar.code = r.coa_receivable_code LEFT JOIN coa_accounts rv ON rv.code = r.coa_revenue_code {$where} ORDER BY r.room_code ASC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage), $params);
        respond(['data' => array_map(static fn (array $room): array => ['id' => as_int($room['id']), 'code' => $room['room_code'], 'name' => $room['room_name'], 'roomTypeId' => as_int($room['room_type_id']), 'type' => $room['room_type_name'], 'rate' => as_float($room['base_rate']), 'coaReceivableCode' => $room['coa_receivable_code'], 'coaReceivable' => $room['coa_receivable_code'] ? $room['coa_receivable_code'] . ' - ' . ($room['receivable_name'] ?? '') : '', 'coaRevenueCode' => $room['coa_revenue_code'], 'coaRevenue' => $room['coa_revenue_code'] ? $room['coa_revenue_code'] . ' - ' . ($room['revenue_name'] ?? '') : '', 'status' => ucfirst((string) $room['status']), 'floor' => $room['floor'], 'note' => $room['notes'] ?? '', 'hk' => $room['status'] === 'occupied' ? 'Guest in house' : 'Vacant clean', 'no' => $room['room_code']], $rows), 'meta' => paginate_meta($page, $perPage, $total)]);
    }
    if ($method === 'POST' && $path === 'rooms') { $payload = json_input(); require_fields($payload, ['code', 'name', 'roomTypeId']); if (db_one($db, "SELECT id FROM rooms WHERE room_code = ?", [trim((string) $payload['code'])])) fail('Kode kamar sudah dipakai.', 422, ['code' => ['Kode kamar sudah dipakai.']]); $db->prepare("INSERT INTO rooms (room_type_id, room_code, room_name, coa_receivable_code, coa_revenue_code, status, floor, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")->execute([as_int($payload['roomTypeId']), trim((string) $payload['code']), trim((string) $payload['name']), trim((string) ($payload['coaReceivableCode'] ?? '')) ?: null, trim((string) ($payload['coaRevenueCode'] ?? '')) ?: null, strtolower(trim((string) ($payload['status'] ?? 'available'))), trim((string) ($payload['floor'] ?? '')) ?: null, trim((string) ($payload['notes'] ?? '')) ?: null, now_ts(), now_ts()]); respond(['message' => 'Master kamar berhasil ditambahkan.'], 201); }
    if ($method === 'PUT' && ($params = match_route('rooms/{code}', $path)) !== null) { $payload = json_input(); require_fields($payload, ['name', 'roomTypeId']); $db->prepare("UPDATE rooms SET room_type_id=?, room_name=?, coa_receivable_code=?, coa_revenue_code=?, status=?, floor=?, notes=?, updated_at=? WHERE room_code=?")->execute([as_int($payload['roomTypeId']), trim((string) $payload['name']), trim((string) ($payload['coaReceivableCode'] ?? '')) ?: null, trim((string) ($payload['coaRevenueCode'] ?? '')) ?: null, strtolower(trim((string) ($payload['status'] ?? 'available'))), trim((string) ($payload['floor'] ?? '')) ?: null, trim((string) ($payload['notes'] ?? '')) ?: null, now_ts(), $params['code']]); respond(['message' => 'Master kamar berhasil diperbarui.']); }

    if ($method === 'GET' && $path === 'bookings') {
        $page = max(1, as_int(q('page', 1))); $perPage = min(max(as_int(q('per_page', 12)), 1), 100); $search = trim((string) q('search', '')); $where = ''; $params = [];
        if ($search !== '') { $like = '%' . $search . '%'; $where = "WHERE (b.booking_code LIKE ? OR b.source LIKE ? OR b.status LIKE ? OR g.full_name LIKE ? OR g.phone LIKE ? OR g.email LIKE ? OR EXISTS (SELECT 1 FROM booking_rooms br2 JOIN rooms r2 ON r2.id = br2.room_id WHERE br2.booking_id = b.id AND r2.room_code LIKE ?))"; $params = [$like, $like, $like, $like, $like, $like, $like]; }
        $total = (int) db_value($db, "SELECT COUNT(*) FROM bookings b JOIN guests g ON g.id = b.guest_id {$where}", $params);
        $rows = db_all($db, "SELECT b.*, g.full_name AS guest_name, g.phone AS guest_phone, g.email AS guest_email FROM bookings b JOIN guests g ON g.id = b.guest_id {$where} ORDER BY b.id DESC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage), $params);
        respond(['data' => array_map(fn (array $row): array => transform_booking($db, $row), $rows), 'meta' => paginate_meta($page, $perPage, $total)]);
    }
    if ($method === 'GET' && ($params = match_route('bookings/{code}', $path)) !== null) { $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404); respond(['data' => transform_booking($db, $booking)]); }
    if ($method === 'POST' && $path === 'bookings') {
        $payload = json_input(); require_fields($payload, ['guest', 'checkIn', 'checkOut', 'channel', 'status', 'roomDetails']); if (!is_array($payload['roomDetails']) || count($payload['roomDetails']) < 1) fail('Minimal satu kamar wajib dipilih.', 422, ['roomDetails' => ['Minimal satu kamar wajib dipilih.']]);
        ensure_rooms_available($db, $payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut'], null); $db->beginTransaction();
        try { $guestId = guest_upsert($db, null, $payload); $bookingCode = generate_booking_code($db, (string) $payload['checkIn']); $roomAmount = calculate_room_amount($payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut']);
            $db->prepare("INSERT INTO bookings (booking_code, guest_id, source, status, check_in_at, check_out_at, room_amount, addon_amount, discount_amount, tax_amount, grand_total, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 0, 0, 0, ?, ?, ?, ?)")->execute([$bookingCode, $guestId, normalize_source((string) $payload['channel']), normalize_booking_status((string) $payload['status']), $payload['checkIn'], $payload['checkOut'], $roomAmount, $roomAmount, trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), now_ts()]);
            $bookingId = (int) $db->lastInsertId(); sync_booking_rooms($db, $bookingId, $payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut']); sync_booking_financial_state($db, $bookingId); $db->commit(); $booking = load_booking_row($db, $bookingCode);
            audit_log($db, ['module' => 'bookings', 'action' => 'created', 'entity_type' => 'booking', 'entity_id' => $bookingId, 'entity_label' => $bookingCode, 'description' => "Booking {$bookingCode} dibuat untuk " . trim((string) $payload['guest']) . '.', 'metadata' => ['status' => normalize_booking_status((string) $payload['status']), 'source' => normalize_source((string) $payload['channel']), 'grand_total' => $roomAmount]], $actor);
            respond(['data' => transform_booking($db, $booking), 'message' => 'Reservasi berhasil disimpan ke database.'], 201);
        } catch (Throwable $e) { if ($db->inTransaction()) $db->rollBack(); throw $e; }
    }
    if ($method === 'PUT' && ($params = match_route('bookings/{code}', $path)) !== null) {
        $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404);
        $payload = json_input(); require_fields($payload, ['guest', 'checkIn', 'checkOut', 'channel', 'status', 'roomDetails']); if (!is_array($payload['roomDetails']) || count($payload['roomDetails']) < 1) fail('Minimal satu kamar wajib dipilih.', 422, ['roomDetails' => ['Minimal satu kamar wajib dipilih.']]);
        ensure_rooms_available($db, $payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut'], as_int($booking['id'])); $db->beginTransaction();
        try { $guestId = guest_upsert($db, as_int($booking['guest_id']), $payload); $roomAmount = calculate_room_amount($payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut']); $grandTotal = $roomAmount + as_float($booking['addon_amount']) - as_float($booking['discount_amount']) + as_float($booking['tax_amount']);
            $db->prepare("UPDATE bookings SET guest_id=?, source=?, status=?, check_in_at=?, check_out_at=?, room_amount=?, grand_total=?, notes=?, updated_at=? WHERE id=?")->execute([$guestId, normalize_source((string) $payload['channel']), normalize_booking_status((string) $payload['status']), $payload['checkIn'], $payload['checkOut'], $roomAmount, $grandTotal, trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), $booking['id']]);
            sync_booking_rooms($db, as_int($booking['id']), $payload['roomDetails'], (string) $payload['checkIn'], (string) $payload['checkOut']); sync_booking_financial_state($db, as_int($booking['id'])); $db->commit(); $fresh = load_booking_row($db, $params['code']);
            respond(['data' => transform_booking($db, $fresh), 'message' => 'Reservasi berhasil diperbarui.']);
        } catch (Throwable $e) { if ($db->inTransaction()) $db->rollBack(); throw $e; }
    }
    if ($method === 'PATCH' && ($params = match_route('bookings/{code}/status', $path)) !== null) {
        $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404);
        $payload = json_input(); require_fields($payload, ['status']); $targetStatus = normalize_booking_status((string) $payload['status']); $currentStatus = (string) $booking['status'];
        if ($targetStatus === 'checked_in' && !in_array($currentStatus, ['draft', 'confirmed'], true)) fail('Hanya booking Tentative atau Confirmed yang bisa di-check-in.', 422, ['status' => ['Hanya booking Tentative atau Confirmed yang bisa di-check-in.']]);
        if ($targetStatus === 'checked_out') { if ($currentStatus !== 'checked_in') fail('Hanya booking Checked-in yang bisa di-check-out.', 422, ['status' => ['Hanya booking Checked-in yang bisa di-check-out.']]); $invoice = db_one($db, "SELECT * FROM invoices WHERE booking_id = ? LIMIT 1", [$booking['id']]); if ($invoice && as_float($invoice['balance_due']) > 0) fail('Tidak bisa Check-out. Tamu belum melunasi tagihan (Sisa: ' . money(as_float($invoice['balance_due'])) . '). Silakan lakukan pembayaran terlebih dahulu di menu Finance / Folio.', 422, ['status' => ['Invoice belum lunas.']]); }
        $db->beginTransaction();
        try { $db->prepare("UPDATE bookings SET status=?, updated_at=? WHERE id=?")->execute([$targetStatus, now_ts(), $booking['id']]); if ($targetStatus === 'checked_in' || $targetStatus === 'checked_out') { $roomIds = db_all($db, "SELECT room_id FROM booking_rooms WHERE booking_id = ?", [$booking['id']]); $status = $targetStatus === 'checked_in' ? 'occupied' : 'dirty'; $up = $db->prepare("UPDATE rooms SET status=?, updated_at=? WHERE id=?"); foreach ($roomIds as $row) $up->execute([$status, now_ts(), $row['room_id']]); } $db->commit(); }
        catch (Throwable $e) { if ($db->inTransaction()) $db->rollBack(); throw $e; }
        $fresh = load_booking_row($db, $params['code']); respond(['data' => transform_booking($db, $fresh), 'message' => $targetStatus === 'checked_in' ? 'Tamu berhasil check-in.' : 'Tamu berhasil check-out.']);
    }
    if ($method === 'POST' && ($params = match_route('bookings/{code}/addons', $path)) !== null) {
        $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404); $payload = json_input(); require_fields($payload, ['addonType', 'serviceName', 'addonLabel', 'unitPriceValue', 'status']);
        $quantity = max(1, as_int($payload['quantity'] ?? 1)); $unitPrice = as_float($payload['unitPriceValue']);
        $db->prepare("INSERT INTO booking_addons (booking_id, addon_type, reference_id, service_date, start_date, end_date, qty, unit_price, total_price, status, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")->execute([$booking['id'], trim((string) $payload['addonType']), is_numeric($payload['referenceId'] ?? null) ? as_int($payload['referenceId']) : null, $payload['serviceDate'] ?? $payload['startDate'] ?? substr((string) $booking['check_in_at'], 0, 10), $payload['startDate'] ?? $payload['serviceDate'] ?? substr((string) $booking['check_in_at'], 0, 10), $payload['endDate'] ?? null, $quantity, $unitPrice, $unitPrice * $quantity, normalize_addon_status((string) $payload['status']), json_encode(['note' => trim((string) ($payload['notes'] ?? '')), 'serviceName' => trim((string) $payload['serviceName']), 'addonLabel' => trim((string) $payload['addonLabel']), 'itemRef' => trim((string) ($payload['referenceId'] ?? ''))], JSON_UNESCAPED_UNICODE), now_ts(), now_ts()]);
        sync_booking_financial_state($db, as_int($booking['id'])); $fresh = load_booking_row($db, $params['code']); respond(['data' => transform_booking($db, $fresh), 'message' => 'Add-on berhasil ditautkan ke reservasi.'], 201);
    }
    if ($method === 'PATCH' && ($params = match_route('bookings/{code}/addons/{id}', $path)) !== null) { $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404); $payload = json_input(); require_fields($payload, ['status']); $db->prepare("UPDATE booking_addons SET status=?, updated_at=? WHERE id=? AND booking_id=?")->execute([normalize_addon_status((string) $payload['status']), now_ts(), $params['id'], $booking['id']]); sync_booking_financial_state($db, as_int($booking['id'])); $fresh = load_booking_row($db, $params['code']); respond(['data' => transform_booking($db, $fresh), 'message' => 'Status add-on berhasil diperbarui.']); }
    if ($method === 'DELETE' && ($params = match_route('bookings/{code}/addons/{id}', $path)) !== null) { $booking = load_booking_row($db, $params['code']); if (!$booking) fail('Booking tidak ditemukan.', 404); $db->prepare("DELETE FROM booking_addons WHERE id=? AND booking_id=?")->execute([$params['id'], $booking['id']]); sync_booking_financial_state($db, as_int($booking['id'])); $fresh = load_booking_row($db, $params['code']); respond(['data' => transform_booking($db, $fresh), 'message' => 'Add-on berhasil dihapus dari reservasi.']); }

    if ($method === 'GET' && $path === 'payments') { $rows = db_all($db, "SELECT * FROM payments ORDER BY id DESC"); respond(['data' => array_map(fn (array $row): array => payment_transform($db, $row), $rows)]); }
    if ($method === 'POST' && $path === 'payments') {
        $payload = json_input(); require_fields($payload, ['bookingCode', 'amountValue', 'method', 'paymentDate']); $booking = load_booking_row($db, trim((string) $payload['bookingCode'])); if (!$booking) fail('Booking tidak ditemukan.', 422, ['bookingCode' => ['Booking tidak ditemukan.']]);
        sync_booking_financial_state($db, as_int($booking['id'])); $invoice = db_one($db, "SELECT * FROM invoices WHERE booking_id = ? LIMIT 1", [$booking['id']]); if (!$invoice) fail('Invoice untuk reservasi ini tidak ditemukan.', 422, ['bookingCode' => ['Invoice untuk reservasi ini tidak ditemukan.']]);
        $amount = as_float($payload['amountValue']); if ($amount > as_float($invoice['balance_due'])) fail('Nominal pembayaran melebihi saldo terutang invoice.', 422, ['amountValue' => ['Nominal pembayaran melebihi saldo terutang invoice.']]);
        $db->beginTransaction();
        try { $db->prepare("INSERT INTO payments (payment_number, guest_id, payment_date, payment_method, amount, cash_bank_coa_code, reference_number, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")->execute([generate_payment_code($db), $booking['guest_id'], $payload['paymentDate'], normalize_payment_method((string) $payload['method']), $amount, resolve_cash_bank_coa($db, (string) $payload['method']), trim((string) ($payload['referenceNo'] ?? '')) ?: null, trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), now_ts()]);
            $paymentId = (int) $db->lastInsertId(); $db->prepare("INSERT INTO payment_allocations (payment_id, invoice_id, allocated_amount, created_at, updated_at) VALUES (?, ?, ?, ?, ?)")->execute([$paymentId, $invoice['id'], $amount, now_ts(), now_ts()]);
            $paidAmount = as_float($invoice['paid_amount']) + $amount; $balanceDue = max(0, as_float($invoice['grand_total']) - $paidAmount); $status = $balanceDue <= 0 ? 'paid' : ($paidAmount > 0 ? 'partial' : 'unpaid'); $db->prepare("UPDATE invoices SET paid_amount=?, balance_due=?, status=?, updated_at=? WHERE id=?")->execute([$paidAmount, $balanceDue, $status, now_ts(), $invoice['id']]);
            sync_payment_accounting($db, $paymentId); $db->commit(); $payment = db_one($db, "SELECT * FROM payments WHERE id = ?", [$paymentId]); respond(['data' => payment_transform($db, $payment), 'message' => 'Pembayaran berhasil disimpan.'], 201);
        } catch (Throwable $e) { if ($db->inTransaction()) $db->rollBack(); throw $e; }
    }

    if ($method === 'GET' && $path === 'journals') {
        $page = max(1, as_int(q('page', 1))); $perPage = min(max(as_int(q('per_page', 15)), 1), 100); $search = trim((string) q('search', '')); $where = ''; $params = [];
        if ($search !== '') { $like = '%' . $search . '%'; $where = "WHERE (journal_number LIKE ? OR description LIKE ? OR reference_type LIKE ?)"; $params = [$like, $like, $like]; }
        $total = (int) db_value($db, "SELECT COUNT(*) FROM journals {$where}", $params); $rows = db_all($db, "SELECT * FROM journals {$where} ORDER BY journal_date DESC, journal_number DESC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage), $params); $data = [];
        foreach ($rows as $journal) { $lines = db_all($db, "SELECT * FROM journal_lines WHERE journal_id = ? ORDER BY id ASC", [$journal['id']]); $debit = array_sum(array_map(static fn (array $row): float => as_float($row['debit']), $lines)); $credit = array_sum(array_map(static fn (array $row): float => as_float($row['credit']), $lines)); $data[] = ['id' => as_int($journal['id']), 'journalNo' => $journal['journal_number'], 'journalDate' => $journal['journal_date'], 'referenceNo' => $journal['reference_type'] ?? '', 'description' => $journal['description'], 'debitTotalValue' => $debit, 'creditTotalValue' => $credit, 'lineCount' => count($lines), 'lines' => array_map(static fn (array $line): array => ['id' => as_int($line['id']), 'coaCode' => $line['coa_code'], 'debitValue' => as_float($line['debit']), 'creditValue' => as_float($line['credit']), 'memo' => $line['line_description'] ?? ''], $lines)]; }
        respond(['data' => $data, 'meta' => paginate_meta($page, $perPage, $total)]);
    }
    if (($method === 'POST' && $path === 'journals') || ($method === 'PUT' && ($params = match_route('journals/{id}', $path)) !== null)) {
        $payload = json_input(); require_fields($payload, ['journalDate', 'description', 'lines']); if (!is_array($payload['lines']) || count($payload['lines']) < 2) fail('Minimal dua baris jurnal yang valid wajib diisi.', 422, ['lines' => ['Minimal dua baris jurnal yang valid wajib diisi.']]);
        $lines = []; foreach ($payload['lines'] as $line) { $account = trim((string) ($line['account'] ?? '')); $coaCode = trim((string) strtok($account, '-')); $debit = round(as_float($line['debitValue'] ?? 0), 2); $credit = round(as_float($line['creditValue'] ?? 0), 2); if ($account === '' || ($debit <= 0 && $credit <= 0)) continue; if ($debit > 0 && $credit > 0) fail('Satu baris jurnal hanya boleh berisi debit atau kredit.', 422, ['lines' => ['Satu baris jurnal hanya boleh berisi debit atau kredit.']]); $lines[] = ['coa_code' => $coaCode, 'debit' => $debit, 'credit' => $credit, 'memo' => trim((string) ($line['memo'] ?? ''))]; }
        if (count($lines) < 2) fail('Minimal dua baris jurnal yang valid wajib diisi.', 422, ['lines' => ['Minimal dua baris jurnal yang valid wajib diisi.']]); $debitTotal = array_sum(array_map(static fn (array $line): float => $line['debit'], $lines)); $creditTotal = array_sum(array_map(static fn (array $line): float => $line['credit'], $lines));
        if ($debitTotal <= 0 || $creditTotal <= 0 || abs($debitTotal - $creditTotal) > 0.000001) fail('Total debit dan kredit harus seimbang.', 422, ['lines' => ['Total debit dan kredit harus seimbang.']]);
        $db->beginTransaction();
        try { if ($method === 'POST') { $db->prepare("INSERT INTO journals (journal_number, journal_date, reference_type, description, source, posted_by, created_at, updated_at) VALUES (?, ?, ?, ?, 'manual', NULL, ?, ?)")->execute([generate_journal_number($db, (string) $payload['journalDate']), $payload['journalDate'], trim((string) ($payload['referenceNo'] ?? '')) ?: null, trim((string) $payload['description']), now_ts(), now_ts()]); $journalId = (int) $db->lastInsertId(); }
            else { $journalId = as_int($params['id']); $db->prepare("UPDATE journals SET journal_date=?, reference_type=?, description=?, source='manual', updated_at=? WHERE id=?")->execute([$payload['journalDate'], trim((string) ($payload['referenceNo'] ?? '')) ?: null, trim((string) $payload['description']), now_ts(), $journalId]); $db->prepare("DELETE FROM journal_lines WHERE journal_id=?")->execute([$journalId]); }
            $insert = $db->prepare("INSERT INTO journal_lines (journal_id, coa_code, line_description, debit, credit, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)"); foreach ($lines as $line) $insert->execute([$journalId, $line['coa_code'], $line['memo'] ?: null, $line['debit'], $line['credit'], now_ts(), now_ts()]); $db->commit(); $journal = db_one($db, "SELECT * FROM journals WHERE id = ?", [$journalId]);
            respond(['data' => ['id' => as_int($journalId), 'journalNo' => $journal['journal_number'], 'journalDate' => $journal['journal_date'], 'referenceNo' => $journal['reference_type'] ?? '', 'description' => $journal['description'], 'debitTotalValue' => $debitTotal, 'creditTotalValue' => $creditTotal, 'lineCount' => count($lines), 'lines' => array_map(static fn (array $line): array => ['coaCode' => $line['coa_code'], 'debitValue' => $line['debit'], 'creditValue' => $line['credit'], 'memo' => $line['memo']], $lines)], 'message' => $method === 'POST' ? "Jurnal umum {$journal['journal_number']} berhasil diposting." : "Jurnal umum {$journal['journal_number']} berhasil diperbarui."], $method === 'POST' ? 201 : 200);
        } catch (Throwable $e) { if ($db->inTransaction()) $db->rollBack(); throw $e; }
    }
    if ($method === 'GET' && $path === 'inventory') {
        $items = db_all($db, "SELECT * FROM inventory_items ORDER BY id DESC"); $itemRows = [];
        foreach ($items as $item) { $purchased = as_float(db_value($db, "SELECT COALESCE(SUM(qty_in),0) FROM inventory_movements WHERE item_id = ?", [$item['id']])); $issued = as_float(db_value($db, "SELECT COALESCE(SUM(qty_out),0) FROM inventory_movements WHERE item_id = ?", [$item['id']])); $itemRows[] = ['id' => as_int($item['id']), 'name' => $item['item_name'], 'category' => $item['category'], 'trackingType' => strtolower((string) $item['category']) === 'linen' ? 'Linen' : 'Consumable', 'unit' => $item['unit'], 'purchasedQty' => as_int($purchased), 'issuedQty' => as_int($issued), 'onHandQty' => as_int(max($purchased - $issued, 0)), 'inventoryCoa' => $item['inventory_coa_code'], 'expenseCoa' => $item['expense_coa_code'], 'reorderLevel' => as_int($item['min_stock']), 'latestCostValue' => as_float($item['standard_cost']), 'latestCost' => money(as_float($item['standard_cost']))]; }
        respond(['data' => ['items' => $itemRows, 'purchases' => [], 'issues' => [], 'journalEntries' => [], 'summary' => ['itemCount' => count($itemRows), 'lowStockCount' => count(array_filter($itemRows, static fn (array $row): bool => $row['onHandQty'] <= $row['reorderLevel'])), 'consumableIssueCount' => 0, 'linenIssueCount' => 0]]]);
    }
    if ($method === 'POST' && $path === 'inventory/items') { $payload = json_input(); require_fields($payload, ['name', 'category', 'trackingType', 'unit', 'inventoryCoa', 'expenseCoa']); $db->prepare("INSERT INTO inventory_items (sku, item_name, category, unit, standard_cost, min_stock, inventory_coa_code, expense_coa_code, notes, is_active, created_at, updated_at) VALUES (?, ?, ?, ?, 0, ?, ?, ?, 'Created from inventory UI.', 1, ?, ?)")->execute(['SKU-' . date('YmdHis'), trim((string) $payload['name']), strtolower(trim((string) $payload['category'])), trim((string) $payload['unit']), as_int($payload['reorderLevel'] ?? 0), trim((string) $payload['inventoryCoa']), trim((string) $payload['expenseCoa']), now_ts(), now_ts()]); respond(['message' => "Item {$payload['name']} berhasil ditambahkan ke inventory master."], 201); }
    if ($method === 'POST' && $path === 'inventory/purchases') { $payload = json_input(); require_fields($payload, ['purchaseDate', 'supplier', 'itemId', 'quantity', 'unitCostValue', 'paymentAccount']); $db->prepare("INSERT INTO inventory_movements (item_id, movement_date, movement_type, qty_in, qty_out, unit_cost, reference_type, reference_id, notes, created_at, updated_at) VALUES (?, ?, 'purchase', ?, 0, ?, 'purchase', ?, ?, ?, ?)")->execute([as_int($payload['itemId']), $payload['purchaseDate'] . ' 00:00:00', as_int($payload['quantity']), as_float($payload['unitCostValue']), random_int(100000, 999999), json_encode(['supplier' => trim((string) $payload['supplier']), 'paymentAccount' => trim((string) $payload['paymentAccount']), 'note' => trim((string) ($payload['note'] ?? ''))], JSON_UNESCAPED_UNICODE), now_ts(), now_ts()]); $db->prepare("UPDATE inventory_items SET standard_cost=?, updated_at=? WHERE id=?")->execute([as_float($payload['unitCostValue']), now_ts(), as_int($payload['itemId'])]); respond(['message' => 'Pembelian inventory berhasil diposting.'], 201); }
    if ($method === 'POST' && $path === 'inventory/issues') { $payload = json_input(); require_fields($payload, ['issueDate', 'roomNo', 'itemId', 'quantity']); $item = db_one($db, "SELECT * FROM inventory_items WHERE id = ?", [as_int($payload['itemId'])]); $room = db_one($db, "SELECT * FROM rooms WHERE room_code = ?", [trim((string) $payload['roomNo'])]); if (!$item || !$room) fail('Item inventory atau kamar tidak ditemukan.', 422); $purchased = as_float(db_value($db, "SELECT COALESCE(SUM(qty_in),0) FROM inventory_movements WHERE item_id=?", [$item['id']])); $issued = as_float(db_value($db, "SELECT COALESCE(SUM(qty_out),0) FROM inventory_movements WHERE item_id=?", [$item['id']])); if (($purchased - $issued) < as_int($payload['quantity'])) fail('Stok tidak cukup untuk di-issue ke kamar.', 422); $db->prepare("INSERT INTO inventory_movements (item_id, movement_date, movement_type, qty_in, qty_out, unit_cost, reference_type, reference_id, notes, created_at, updated_at) VALUES (?, ?, 'issue_room', 0, ?, ?, 'room_issue', ?, ?, ?, ?)")->execute([$item['id'], $payload['issueDate'] . ' 00:00:00', as_int($payload['quantity']), as_float($item['standard_cost']), as_int($room['room_code']), json_encode(['note' => trim((string) ($payload['note'] ?? ''))], JSON_UNESCAPED_UNICODE), now_ts(), now_ts()]); respond(['message' => "Item berhasil issue ke kamar {$room['room_code']}."], 201); }

    if ($method === 'GET' && $path === 'transport-rates') { $rows = db_all($db, "SELECT * FROM transport_rates ORDER BY id DESC"); respond(['data' => array_map(static fn (array $row): array => ['id' => 'TRF-' . str_pad((string) $row['id'], 3, '0', STR_PAD_LEFT), 'dbId' => as_int($row['id']), 'driver' => $row['driver'], 'pickupPriceValue' => as_float($row['pickup_price_value']), 'pickupPrice' => money(as_float($row['pickup_price_value'])), 'dropOffPriceValue' => as_float($row['drop_off_price_value']), 'dropOffPrice' => money(as_float($row['drop_off_price_value'])), 'vehicle' => $row['vehicle'], 'note' => $row['note']], $rows)]); }
    if (($method === 'POST' && $path === 'transport-rates') || ($method === 'PUT' && ($params = match_route('transport-rates/{id}', $path)) !== null)) { $payload = json_input(); require_fields($payload, ['driver', 'pickupPriceValue', 'dropOffPriceValue']); if ($method === 'POST') { $db->prepare("INSERT INTO transport_rates (driver, pickup_price_value, drop_off_price_value, vehicle, note, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)")->execute([trim((string) $payload['driver']), as_float($payload['pickupPriceValue']), as_float($payload['dropOffPriceValue']), trim((string) ($payload['vehicle'] ?? '')) ?: null, trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), now_ts()]); respond(['message' => "Driver {$payload['driver']} berhasil ditambahkan."], 201); } $db->prepare("UPDATE transport_rates SET driver=?, pickup_price_value=?, drop_off_price_value=?, vehicle=?, note=?, updated_at=? WHERE id=?")->execute([trim((string) $payload['driver']), as_float($payload['pickupPriceValue']), as_float($payload['dropOffPriceValue']), trim((string) ($payload['vehicle'] ?? '')) ?: null, trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), as_int($params['id'])]); respond(['message' => "Driver {$payload['driver']} berhasil diperbarui."]); }

    if ($method === 'GET' && $path === 'activity-catalog') { $scooters = db_all($db, "SELECT * FROM scooter_catalog ORDER BY id DESC"); $operators = db_all($db, "SELECT * FROM activity_operator_catalog ORDER BY id DESC"); $tours = db_all($db, "SELECT * FROM island_tour_catalog ORDER BY id DESC"); $boats = db_all($db, "SELECT * FROM boat_ticket_catalog ORDER BY id DESC"); respond(['data' => ['scooters' => array_map(static fn (array $row): array => ['id' => 'SCT-' . str_pad((string) $row['id'], 3, '0', STR_PAD_LEFT), 'dbId' => as_int($row['id']), 'startDate' => $row['start_date'], 'endDate' => $row['end_date'], 'scooterType' => $row['scooter_type'], 'vendor' => $row['vendor'], 'priceValue' => as_float($row['price_value']), 'price' => money(as_float($row['price_value']))], $scooters), 'operators' => array_map(static fn (array $row): array => ['id' => 'OPR-' . str_pad((string) $row['id'], 3, '0', STR_PAD_LEFT), 'dbId' => as_int($row['id']), 'operator' => $row['operator'], 'priceValue' => as_float($row['price_value']), 'price' => money(as_float($row['price_value'])), 'note' => $row['note']], $operators), 'islandTours' => array_map(static fn (array $row): array => ['id' => 'TOUR-' . str_pad((string) $row['id'], 3, '0', STR_PAD_LEFT), 'dbId' => as_int($row['id']), 'destination' => $row['destination'], 'driver' => $row['driver'], 'costValue' => as_float($row['cost_value']), 'cost' => money(as_float($row['cost_value'])), 'note' => $row['note']], $tours), 'boatTickets' => array_map(static fn (array $row): array => ['id' => 'BOT-' . str_pad((string) $row['id'], 3, '0', STR_PAD_LEFT), 'dbId' => as_int($row['id']), 'company' => $row['company'], 'destination' => $row['destination'], 'priceValue' => as_float($row['price_value']), 'price' => money(as_float($row['price_value']))], $boats)]]); }
    if (($method === 'POST' && $path === 'activity-catalog/scooters') || ($method === 'PUT' && ($params = match_route('activity-catalog/scooters/{id}', $path)) !== null)) { $payload = json_input(); require_fields($payload, ['startDate', 'endDate', 'scooterType', 'vendor', 'priceValue']); if ($method === 'POST') { $db->prepare("INSERT INTO scooter_catalog (start_date, end_date, scooter_type, vendor, price_value, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)")->execute([$payload['startDate'], $payload['endDate'], trim((string) $payload['scooterType']), trim((string) $payload['vendor']), as_float($payload['priceValue']), now_ts(), now_ts()]); respond(['message' => 'Data scooter berhasil ditambahkan.'], 201); } $db->prepare("UPDATE scooter_catalog SET start_date=?, end_date=?, scooter_type=?, vendor=?, price_value=?, updated_at=? WHERE id=?")->execute([$payload['startDate'], $payload['endDate'], trim((string) $payload['scooterType']), trim((string) $payload['vendor']), as_float($payload['priceValue']), now_ts(), as_int($params['id'])]); respond(['message' => 'Data scooter berhasil diperbarui.']); }
    if (($method === 'POST' && $path === 'activity-catalog/operators') || ($method === 'PUT' && ($params = match_route('activity-catalog/operators/{id}', $path)) !== null)) { $payload = json_input(); require_fields($payload, ['operator', 'priceValue']); if ($method === 'POST') { $db->prepare("INSERT INTO activity_operator_catalog (operator, price_value, note, created_at, updated_at) VALUES (?, ?, ?, ?, ?)")->execute([trim((string) $payload['operator']), as_float($payload['priceValue']), trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), now_ts()]); respond(['message' => 'Data operator berhasil ditambahkan.'], 201); } $db->prepare("UPDATE activity_operator_catalog SET operator=?, price_value=?, note=?, updated_at=? WHERE id=?")->execute([trim((string) $payload['operator']), as_float($payload['priceValue']), trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), as_int($params['id'])]); respond(['message' => 'Data operator berhasil diperbarui.']); }
    if (($method === 'POST' && $path === 'activity-catalog/island-tours') || ($method === 'PUT' && ($params = match_route('activity-catalog/island-tours/{id}', $path)) !== null)) { $payload = json_input(); require_fields($payload, ['destination', 'driver', 'costValue']); if ($method === 'POST') { $db->prepare("INSERT INTO island_tour_catalog (destination, driver, cost_value, note, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)")->execute([trim((string) $payload['destination']), trim((string) $payload['driver']), as_float($payload['costValue']), trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), now_ts()]); respond(['message' => 'Data island tour berhasil ditambahkan.'], 201); } $db->prepare("UPDATE island_tour_catalog SET destination=?, driver=?, cost_value=?, note=?, updated_at=? WHERE id=?")->execute([trim((string) $payload['destination']), trim((string) $payload['driver']), as_float($payload['costValue']), trim((string) ($payload['note'] ?? '')) ?: null, now_ts(), as_int($params['id'])]); respond(['message' => 'Data island tour berhasil diperbarui.']); }
    if (($method === 'POST' && $path === 'activity-catalog/boat-tickets') || ($method === 'PUT' && ($params = match_route('activity-catalog/boat-tickets/{id}', $path)) !== null)) { $payload = json_input(); require_fields($payload, ['company', 'destination', 'priceValue']); if ($method === 'POST') { $db->prepare("INSERT INTO boat_ticket_catalog (company, destination, price_value, created_at, updated_at) VALUES (?, ?, ?, ?, ?)")->execute([trim((string) $payload['company']), trim((string) $payload['destination']), as_float($payload['priceValue']), now_ts(), now_ts()]); respond(['message' => 'Data boat ticket berhasil ditambahkan.'], 201); } $db->prepare("UPDATE boat_ticket_catalog SET company=?, destination=?, price_value=?, updated_at=? WHERE id=?")->execute([trim((string) $payload['company']), trim((string) $payload['destination']), as_float($payload['priceValue']), now_ts(), as_int($params['id'])]); respond(['message' => 'Data boat ticket berhasil diperbarui.']); }

    if ($method === 'GET' && $path === 'dashboard/owner') { $today = today_date(); $roomsTotal = (int) db_value($db, "SELECT COUNT(*) FROM rooms"); $availableRooms = (int) db_value($db, "SELECT COUNT(*) FROM rooms WHERE status='available'"); $inHouse = db_all($db, "SELECT * FROM bookings WHERE status='checked_in' AND DATE(check_in_at) <= ? AND DATE(check_out_at) > ?", [$today, $today]); $roomRevenue = as_float(db_value($db, "SELECT COALESCE(SUM(room_amount),0) FROM bookings WHERE DATE(check_in_at)=?", [$today])); $addonRevenue = as_float(db_value($db, "SELECT COALESCE(SUM(addon_amount),0) FROM bookings WHERE DATE(check_in_at)=?", [$today])); $openFolios = db_all($db, "SELECT * FROM invoices WHERE balance_due > 0 ORDER BY balance_due DESC LIMIT 6"); $outstanding = array_sum(array_map(static fn (array $row): float => as_float($row['balance_due']), $openFolios)); $adr = count($inHouse) > 0 ? $roomRevenue / count($inHouse) : 0; respond(['data' => ['period' => 'today', 'periodLabel' => 'Today', 'rangeLabel' => date('d M Y', strtotime($today)), 'businessDate' => $today, 'currentDateLabel' => date('d F Y', strtotime($today)), 'generatedAt' => date('d M Y H:i'), 'overview' => [['label' => 'Occupancy', 'value' => ($roomsTotal > 0 ? (int) round((count($inHouse) / $roomsTotal) * 100) : 0) . '%', 'note' => count($inHouse) . " room occupied | {$availableRooms} sellable room"], ['label' => 'Arrivals', 'value' => (string) (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE DATE(check_in_at)=?", [$today]), 'note' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE DATE(check_out_at)=?", [$today]) . ' departure today'], ['label' => 'Outstanding', 'value' => money($outstanding), 'note' => count($openFolios) . ' folio still open'], ['label' => 'ADR', 'value' => money($adr), 'note' => 'Room revenue ' . money($roomRevenue)]], 'dailyControl' => [['label' => 'Arrival in range', 'value' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE DATE(check_in_at)=?", [$today])], ['label' => 'Departure in range', 'value' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE DATE(check_out_at)=?", [$today])], ['label' => 'In house snapshot', 'value' => count($inHouse)], ['label' => 'Room still sellable', 'value' => $availableRooms]], 'revenueMix' => [['label' => 'Room revenue', 'value' => money($roomRevenue), 'progress' => 100], ['label' => 'Add-on revenue', 'value' => money($addonRevenue), 'progress' => 100], ['label' => 'Total revenue', 'value' => money($roomRevenue + $addonRevenue), 'progress' => 100], ['label' => 'Open folios', 'value' => count($openFolios) . ' booking(s)', 'progress' => min(count($openFolios) * 12, 100)]], 'arrivalWatch' => [], 'cashierQueue' => [], 'channelPerformance' => [], 'roomTypePerformance' => [], 'liveMovement' => [], 'departmentNotes' => []]]); }
    if ($method === 'GET' && $path === 'night-audit/status') { $today = today_date(); respond(['pending_checkouts' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE status='checked_in' AND DATE(check_out_at) <= ?", [$today]), 'unresolved_arrivals' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE status IN ('confirmed','draft') AND DATE(check_in_at) <= ?", [$today]), 'active_in_house' => (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE status='checked_in' AND check_in_at <= ? AND check_out_at > ?", [$today . ' 23:59:59', $today . ' 00:00:00']), 'audit_date' => date('d M Y', strtotime($today))]); }
    if ($method === 'POST' && $path === 'night-audit') { $today = today_date(); $pending = (int) db_value($db, "SELECT COUNT(*) FROM bookings WHERE status='checked_in' AND DATE(check_out_at) <= ?", [$today]); if ($pending > 0) respond(['message' => 'Proses Night Audit Ditangguhkan! Selesaikan Anomali Pra-Audit ini (Overstay) terlebih dahulu:', 'errors' => ["Terdapat {$pending} tamu overstay yang seharusnya Check-Out hari ini namun sistemnya belum tutup buku (Folio menggantung)."]], 422); $db->prepare("UPDATE bookings SET status='cancelled', updated_at=? WHERE status IN ('confirmed','draft') AND DATE(check_in_at) <= ?")->execute([now_ts(), $today]); respond(['message' => 'Proses Night Audit berhasil diluncurkan dan diselesaikan (Tutup Buku Harian selesai).', 'details' => "Night audit native dijalankan untuk {$today}.", 'data' => ['folios_processed' => 0]]); }

    if ($method === 'GET' && $path === 'roles') { $rows = db_all($db, "SELECT * FROM roles ORDER BY id ASC"); respond(array_map(static fn (array $row): array => ['id' => as_int($row['id']), 'name' => $row['name'], 'permissions' => $row['permissions'] ? (json_decode((string) $row['permissions'], true) ?: []) : []], $rows)); }
    if ($method === 'PUT' && ($params = match_route('roles/{id}/permissions', $path)) !== null) { $payload = json_input(); if (!isset($payload['permissions']) || !is_array($payload['permissions'])) fail('Permissions wajib berupa array.', 422, ['permissions' => ['Permissions wajib berupa array.']]); $db->prepare("UPDATE roles SET permissions=?, updated_at=? WHERE id=?")->execute([json_encode(array_values($payload['permissions']), JSON_UNESCAPED_UNICODE), now_ts(), as_int($params['id'])]); respond(['message' => 'Hak akses berhasil diperbarui!']); }
    if ($method === 'GET' && $path === 'users') { $rows = db_all($db, "SELECT u.id, u.name, u.email, u.is_active, u.role_id, r.name AS role FROM users u LEFT JOIN roles r ON r.id = u.role_id ORDER BY u.id DESC"); respond(array_map(static fn (array $row): array => ['id' => as_int($row['id']), 'name' => $row['name'], 'email' => $row['email'], 'is_active' => (bool) as_int($row['is_active']), 'role_id' => as_int($row['role_id']), 'role' => $row['role'] ?: 'frontdesk'], $rows)); }
    if ($method === 'POST' && $path === 'users') { $payload = json_input(); require_fields($payload, ['name', 'email', 'password', 'role_id']); if (db_one($db, "SELECT id FROM users WHERE email = ?", [trim((string) $payload['email'])])) fail('Email sudah digunakan.', 422, ['email' => ['Email sudah digunakan.']]); $db->prepare("INSERT INTO users (name, email, password, role_id, is_active, created_at, updated_at) VALUES (?, ?, ?, ?, 1, ?, ?)")->execute([trim((string) $payload['name']), trim((string) $payload['email']), password_hash((string) $payload['password'], PASSWORD_BCRYPT), as_int($payload['role_id']), now_ts(), now_ts()]); respond(['message' => 'Akun staf berhasil dibuat!', 'user_id' => (int) $db->lastInsertId()], 201); }
    if ($method === 'PUT' && ($params = match_route('users/{id}', $path)) !== null) { $payload = json_input(); require_fields($payload, ['name', 'email', 'role_id']); $existing = db_one($db, "SELECT id FROM users WHERE email = ? AND id != ?", [trim((string) $payload['email']), as_int($params['id'])]); if ($existing) fail('Email sudah digunakan.', 422, ['email' => ['Email sudah digunakan.']]); $fields = ['name = ?', 'email = ?', 'role_id = ?', 'updated_at = ?']; $values = [trim((string) $payload['name']), trim((string) $payload['email']), as_int($payload['role_id']), now_ts()]; if (array_key_exists('is_active', $payload)) { $fields[] = 'is_active = ?'; $values[] = $payload['is_active'] ? 1 : 0; } if (trim((string) ($payload['password'] ?? '')) !== '') { $fields[] = 'password = ?'; $values[] = password_hash((string) $payload['password'], PASSWORD_BCRYPT); } $values[] = as_int($params['id']); $db->prepare("UPDATE users SET " . implode(', ', $fields) . " WHERE id = ?")->execute($values); respond(['message' => 'Akun staf berhasil diperbarui!']); }
    if ($method === 'PATCH' && ($params = match_route('users/{id}/toggle', $path)) !== null) { $user = db_one($db, "SELECT * FROM users WHERE id = ?", [as_int($params['id'])]); if (!$user) fail('Akun staf tidak ditemukan.', 404); $newStatus = as_int($user['is_active']) ? 0 : 1; $db->prepare("UPDATE users SET is_active=?, updated_at=? WHERE id=?")->execute([$newStatus, now_ts(), $user['id']]); respond(['message' => $newStatus ? 'Akun staf berhasil diaktifkan!' : 'Akun staf berhasil dinonaktifkan!']); }

    if ($method === 'GET' && $path === 'reports/profit-loss') { $roomRevenue = as_float(db_value($db, "SELECT COALESCE(SUM(room_amount),0) FROM bookings WHERE status NOT IN ('cancelled','no_show')")); $addonRevenue = as_float(db_value($db, "SELECT COALESCE(SUM(total_price),0) FROM booking_addons WHERE status != 'cancelled'")); respond(['data' => ['revenue' => ['room' => $roomRevenue, 'addon' => $addonRevenue, 'total' => $roomRevenue + $addonRevenue], 'expense' => ['total' => 0], 'netProfit' => $roomRevenue + $addonRevenue, 'revenues' => [], 'expenses' => [], 'total_revenue' => $roomRevenue + $addonRevenue, 'total_expense' => 0, 'net_profit' => $roomRevenue + $addonRevenue]]); }
    if ($method === 'GET' && $path === 'reports/balance-sheet') { respond(['data' => ['assets' => [], 'liabilities' => [], 'equities' => [], 'total_asset' => 0, 'total_liability_and_equity' => 0]]); }
    if ($method === 'GET' && $path === 'reports/cash-flow') { respond(['data' => ['inflow' => ['guest_payments' => 0, 'manual_journals' => 0, 'total' => 0], 'outflow' => ['expenses' => 0, 'total' => 0], 'netCashFlow' => 0, 'inflows' => [], 'outflows' => [], 'total_inflow' => 0, 'total_outflow' => 0, 'net_cash_flow' => 0]]); }
    if ($method === 'GET' && $path === 'reports/reconciliation') { respond(['data' => ['summary' => ['booking_issue_count' => 0, 'payment_issue_count' => 0, 'bookings_checked' => 0, 'payments_checked' => 0], 'bookingRows' => [], 'paymentRows' => []]]); }
    if ($method === 'POST' && $path === 'accounting/sync-history') { $bookingIds = db_all($db, "SELECT id FROM bookings ORDER BY id ASC"); foreach ($bookingIds as $row) sync_booking_financial_state($db, as_int($row['id'])); $paymentIds = db_all($db, "SELECT id FROM payments ORDER BY id ASC"); foreach ($paymentIds as $row) sync_payment_accounting($db, as_int($row['id'])); respond(['message' => 'Sinkronisasi accounting historis berhasil dijalankan.', 'data' => ['bookings_synced' => count($bookingIds), 'payments_synced' => count($paymentIds)]]); }
    if ($method === 'GET' && $path === 'audit-trails') { $page = max(1, as_int(q('page', 1))); $perPage = min(max(as_int(q('per_page', 20)), 1), 100); $search = trim((string) q('search', '')); $module = trim((string) q('module', '')); $where = []; $params = []; if ($module !== '') { $where[] = "module = ?"; $params[] = $module; } if ($search !== '') { $like = '%' . $search . '%'; $where[] = "(user_name LIKE ? OR user_email LIKE ? OR entity_label LIKE ? OR description LIKE ?)"; array_push($params, $like, $like, $like, $like); } $whereSql = $where ? 'WHERE ' . implode(' AND ', $where) : ''; $total = (int) db_value($db, "SELECT COUNT(*) FROM audit_trails {$whereSql}", $params); $rows = db_all($db, "SELECT * FROM audit_trails {$whereSql} ORDER BY id DESC LIMIT {$perPage} OFFSET " . (($page - 1) * $perPage), $params); respond(['data' => array_map(static fn (array $row): array => ['id' => as_int($row['id']), 'createdAt' => $row['created_at'], 'module' => $row['module'], 'action' => $row['action'], 'userName' => $row['user_name'] ?: 'System', 'userEmail' => $row['user_email'] ?: '-', 'userRole' => $row['user_role'] ?: '-', 'entityType' => $row['entity_type'] ?: '-', 'entityId' => $row['entity_id'] ?: '-', 'entityLabel' => $row['entity_label'] ?: '-', 'description' => $row['description'], 'metadata' => $row['metadata'] ? (json_decode((string) $row['metadata'], true) ?: []) : [], 'ipAddress' => $row['ip_address'] ?: '-'], $rows), 'meta' => paginate_meta($page, $perPage, $total)]); }

    fail('Endpoint tidak ditemukan.', 404);
} catch (PDOException $e) { fail('Terjadi kesalahan database: ' . $e->getMessage(), 500); }
catch (Throwable $e) { fail('Terjadi kesalahan server: ' . $e->getMessage(), 500); }
