INSERT INTO coa_accounts (code, account_name, category, normal_balance, is_active, note, created_at, updated_at) VALUES
('111001', 'Kas Udara', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111002', 'Kas Tenty', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111003', 'Kas Besar', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111004', 'Merchand BCA', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111005', 'BCA 146.5050.600 Fuad', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111006', 'BCA EV 7705.345.678 Evelyn', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111007', 'BRI', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111008', 'BLU', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111009', 'BCA Proyek', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111010', 'Credit Card Alkasa', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111011', 'Prive Fuad', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111012', 'Bank Mandiri', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('111013', 'BCA Sam', 'asset', 'debit', 1, 'Kas dan Setara Kas', NOW(), NOW()),
('112001', 'Piutang Dagang', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('113001', 'Piutang Karyawan', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('114001', 'Piutang Alkasa', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('114002', 'Piutang Kulkul', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('114003', 'Piutang Lain', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('114004', 'Piutang Kaca Ayu', 'asset', 'debit', 1, 'Piutang', NOW(), NOW()),
('115001', 'Persediaan Barang', 'asset', 'debit', 1, 'Persediaan & Uang Muka', NOW(), NOW()),
('116001', 'Sewa Bayar Dimuka', 'asset', 'debit', 1, 'Persediaan & Uang Muka', NOW(), NOW()),
('116002', 'Uang Muka Pembelian', 'asset', 'debit', 1, 'Persediaan & Uang Muka', NOW(), NOW()),
('120000', 'Inventaris', 'asset', 'debit', 1, 'Aktiva Tetap', NOW(), NOW()),
('120001', 'Akum. Peny. Inventaris', 'asset', 'credit', 1, 'Aktiva Tetap', NOW(), NOW()),
('120002', 'Room 5 sd 8', 'asset', 'debit', 1, 'Aktiva Tetap', NOW(), NOW()),
('120003', 'Tanah Bias', 'asset', 'debit', 1, 'Aktiva Tetap', NOW(), NOW()),
('411017', 'Penjualan Bunga', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411018', 'Airbnb', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411019', 'Refund Kamar', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411020', 'Kompensasi', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411021', 'Pendapatan Lain', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411022', 'Penjualan Food / Drink', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('411023', 'Booking.com', 'revenue', 'credit', 1, 'Pendapatan Usaha', NOW(), NOW()),
('510001', 'Pendapatan Pickup/ Drop', 'revenue', 'credit', 1, 'Pendapatan Luar Usaha', NOW(), NOW()),
('510002', 'Pendapatan Scooter', 'revenue', 'credit', 1, 'Pendapatan Luar Usaha', NOW(), NOW()),
('510003', 'Pendapatan Manta', 'revenue', 'credit', 1, 'Pendapatan Luar Usaha', NOW(), NOW()),
('510004', 'Pendapatan Ticket Boat', 'revenue', 'credit', 1, 'Pendapatan Luar Usaha', NOW(), NOW()),
('510005', 'Pendapatan Tour', 'revenue', 'credit', 1, 'Pendapatan Luar Usaha', NOW(), NOW()),
('610001', 'Biaya Kantor', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610002', 'Biaya Listrik', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610003', 'Biaya Air', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610004', 'Biaya Tunjangan Karyawan', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610005', 'Biaya Bank', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610006', 'Biaya Transport / ONGKIR', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610007', 'Biaya Pemlh Kendaraan', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610008', 'Biaya Telpon', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610009', 'Biaya Gaji', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610010', 'Biaya Sewa', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610011', 'Biaya Sabun, Shampoo, Hand Soap', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610012', 'Biaya Internet', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610013', 'Biaya BF', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610014', 'Biaya Maintenance', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610015', 'Biaya Aqua Tanggung, Aqua Galon', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610016', 'Biaya Kopi, Teh, Susu, Gula dll', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610017', 'Biaya Pool', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610018', 'Biaya Card', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW()),
('610019', 'Peralatan Kamar', 'expense', 'debit', 1, 'Biaya Administrasi', NOW(), NOW())
ON DUPLICATE KEY UPDATE
account_name = VALUES(account_name),
category = VALUES(category),
normal_balance = VALUES(normal_balance),
is_active = VALUES(is_active),
note = VALUES(note),
updated_at = VALUES(updated_at);
